# Generated by Django 2.2.2 on 2019-06-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_corp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('sender', models.CharField(max_length=50)),
                ('received', models.DateTimeField(max_length=50)),
                ('received_datetime', models.DateTimeField(max_length=50)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
