# Generated by Django 2.2.2 on 2019-06-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mailbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='received_datetime',
        ),
    ]
